language: r
pandoc_version: 2.1.1
before_install:
  - npm install netlify-cli -g
  - cd book
sudo: false
cache:
  packages: true
  directories:
  - book/_bookdown_files
  - $HOME/.npm
addons:
  apt:
    packages:
    - libgsl0-dev
    - libxml2-dev
    - libudunits2-dev

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'
- cp android-chrome-192x192.png android-chrome-512x512.png apple-touch-icon.png browserconfig.xml favicon-16x16.png favicon-32x32.png favicon.ico mstile-150x150.png safari-pinned-tab.svg site.webmanifest ../_book_output

deploy:
  provider: script
  script: cd .. && netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
